student/config/routes.rb
Rails.application.routes.draw do
	
  devise_for :authors
	root to: 'blog/posts#index'

	namespace :authors do
		resources :posts do
			put 'publish' => 'posts#publish', on: :member
			put 'unpublish' => 'posts#unpublish', on: :member
		end
	end

	scope module:'blog' do
		get 'about'=> 'pages#about', as: :about
		get 'contact'=> 'pages#contact', as: :contact
  		get 'posts' => 'posts#index', as: :posts
  		get 'posts/:id' => 'posts#show', as: :post
  	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

student/app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

student/app/models/post.rb
class Post < ApplicationRecord
	acts_as_taggable # Alias for acts_as_taggable_on :tags
	
	extend FriendlyId
	friendly_id :title, use: :slugged

	belongs_to :author

	PER_PAGE = 3

	scope :most_recent, -> { order(published_at: :desc) }
	scope :published, -> { where(published: true) }
	scope :recent_paginated, -> (page) { most_recent.paginate(page: page, per_page: PER_PAGE) }
	scope :with_tag, -> (tag) { tagged_with(tag) if tag.present? }

	scope :list_for, -> (page, tag) do
		recent_paginated(page).with_tag(tag)
	end

	def should_generate_new_friendly_id?
		title_changed?
	end

	def display_day_published
		if published_at.present?
			"Publicado #{published_at.strftime('%-b %-d, %Y')}"			
		else
			"Not published yet."
		end
	end
end

student/app/controllers/author/posts_controller.rb
module Author
class PostsController < AuthorController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.most_recent
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to author_post_path(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to author_post_path(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to author_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :description, :banner_image_url)
    end
end

end

student/app/controllers/author_controller.rb
class AuthorController < ApplicationController
	before_action :authenticate_author!
end

student/app/controllers/authors/posts_controller.rb
module Authors
class PostsController < AuthorController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

  # GET /posts
  # GET /posts.json
  def index
    @posts = current_author.posts.most_recent
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_author.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  def publish
    @post.update(published: true)
    @post.update(published_at: Time.now)    
    redirect_to authors_posts_url
  end

  def unpublish
    @post.update(published: false)
    @post.update(published_at: nil)    
    redirect_to authors_posts_url
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_author.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.'}
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_author.posts.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :description, :banner_image_url, :tag_list)
    end
end

end

student/app/controllers/blog/posts_controller.rb
module Blog
	class PostsController < BlogController

	  # GET /posts
	  # GET /posts.json
	  def index
	  	@posts = storage.list_for(params[:page], params[:tag])
	  end

	  # GET /posts/1
	  # GET /posts/1.json
	  def show
	  	@post = storage.published.friendly.find(params[:id])
	  end

	  private

	  def storage
	  	Post.published
	  end
	end

end

student/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.most_recent
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :description, :banner_image_url)
    end
end

student/app/helpers/posts_helper.rb
module PostsHelper
end

student/app/views/authors/posts/_form.html.erb
<%= form_for(post, url: url) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class=col-md-3>
    <br>
      <div class="card">
        <div class="card-block" >
          <%if @post.new_record? %> 
            <h4 class="card-title">New Post</h4>
          <%else%>
            <h4 class="card-title">
              <b>Edit</b>
              <span class="thin-text"><%= @post.title %></span>
            </h4>
          <%end%>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="field">
              <%= f.label :title, class: "control-label" %>
              <%= f.text_field :title, class: "form-control", placeholder: "Someone cool title" %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= f.label :banner_image_url, class: "control-label" %>
              <%= f.text_field :banner_image_url, class: "form-control", placeholder: "www.coolimagen.com/yourimage..."%>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= f.label :description, class: "control-label" %>
              <%= f.text_area :description, class: "form-control areas", placeholder: "A bit of all" %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= f.label 'Tags', class: "control-label" %>
              <%= f.text_area :tag_list, class: "form-control areas",  placeholder: "Example. cool, smart, sexy, ..." %>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class=col-md-9>
      <div class="field">
        <%= f.label :body, class: "text-muted" %>
        <%= f.text_area :body %>
      </div>
    </div>
    <div class=col-md-3>
      <div class="actions" id="save">
        <%= f.submit "Save Blog Post", class: "btn btn-lg btn-success btn-block" %>
      </div>
    </div>
  </div>
  <div class="btn-group" role="group" aria-label="...">
    <%if @post.persisted? %>
      <%= link_to 'Show', @post, class: "btn btn-primary" %> 
    <%end%>
      <%= link_to 'Back', authors_posts_path, class: "btn btn-info" %>
  </div>
  <p class="text-muted">If you want see the source of body, you have to click in <em>Tools</em> and <em>Source Code.</em></p>
<% end %>

student/app/views/authors/posts/_post.html.erb
<tr>
	<td><%= link_to post.title, authors_post_path(post) %></td>
	<td></td>
	<%if post.published? %>
		<td><%= link_to 'Unpublish', unpublish_authors_post_path(post), method: :put, class:"btn btn-sm btn-primary" %></td>
	<%else%>
		<td><%= link_to 'Publish', publish_authors_post_path(post), method: :put, class:"btn btn-sm btn-success" %></td> 
	<%end%>
	<td><%= link_to 'Edit', edit_authors_post_path(post), class:"btn btn-sm btn-warning" %></td>
	<td><%= link_to 'Remove', authors_post_path(post), method: :delete, data: {confirm: '¿Are you sure?'}, class:"btn btn-sm btn-danger"%></td>
</tr>

student/app/views/authors/posts/edit.html.erb
<% provide(:page_title, "Edit #{@post.title}") %>
<% provide(:author, 'active') %>

<%= render 'form', post: @post, url:authors_post_url(@post) %>

student/app/views/authors/posts/index.html.erb
<% provide(:page_title, 'All Posts') %>
<% provide(:author, 'active') %>
<div class="row">
	<div>
		<%= link_to 'New Post', new_authors_post_path, class: 'btn btn-primary btn-lg'%>
	</div>
	<br>
  	<table class="table table-striped">
  		<tr>
  			<th colspan="5">Title</th>
  		</tr>
  		<%= render @posts %>
  	</table>
 
  
</div>

student/app/views/authors/posts/new.html.erb
<% provide(:page_title, 'New Post') %>
<% provide(:author, 'active') %>

<%= render 'form', post: @post, url:authors_posts_url %>

student/app/views/authors/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:author, 'active') %>

<div>
	<%= link_to 'Edit', edit_authors_post_path(@post), class:'btn btn-sm btn-warning' %>
	<%= link_to 'Remove', authors_post_path(@post), method: :delete, data: {confirm: '¿Are you sure?'}, class:'btn btn-sm btn-danger'%>
</div>

<div class="row">
	<div class="col-md-12 col-lg-12 text-xs-center">
		<h1><%= @post.title %></h1>
		<p><%= @post.display_day_published %></p>
		<%= @post.body.html_safe %>
	</div>
</div>